version: '1'

services:
  app:
    image: monapp:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    env_file: .env
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:3333/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:17.2
    container_name: app-postgres
    ports:
      - '5432:5432'
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
